spring:
  application:
    name: claim-check
  jackson:
    default-property-inclusion: non_null
management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
server:
  error:
    include-message: never
