create table claim_registration (
    id bigint generated by default as identity primary key,
    claim_id varchar(32) not null,
    fingerprint char(64) not null,
    idempotency_key varchar(200),
    registered_at timestamp with time zone not null default current_timestamp,
    constraint uq_claim_registration_fingerprint unique (fingerprint),
    constraint uq_claim_registration_idempotency_key unique (idempotency_key)
);
